export const ROLES = {
  ADMIN: "ADMIN",
  TRAINER: "TRAINER",
  PARTICIPANT: "PARTICIPANT",
};

export const PERMISSIONS = {
  VIEW_DASHBOARD: "VIEW_DASHBOARD",
  REQUEST_SHIFT: "REQUEST_SHIFT",
  VIEW_SHIFT_HISTORY: "VIEW_SHIFT_HISTORY",
  ACCESS_SUPPORT_NOTES: "ACCESS_SUPPORT_NOTES",
  UPDATE_AVAILABILITY: "UPDATE_AVAILABILITY",
  MANAGE_BOOKINGS: "MANAGE_BOOKINGS",
  CLOCK_IN: "CLOCK_IN",
  CLOCK_OUT: "CLOCK_OUT",
  SUBMIT_SHIFT_REPORT: "SUBMIT_SHIFT_REPORT",
  MANAGE_USERS: "MANAGE_USERS",
  MANAGE_SHIFTS: "MANAGE_SHIFTS",
  MANAGE_DOCUMENTS: "MANAGE_DOCUMENTS",
};
